[package]
name = "sol_beast"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.40", features = ["full"] }
tokio-tungstenite = { version = "0.24", features = ["native-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12", features = ["json"] }
futures-util = "0.3"
log = "0.4"
env_logger = "0.11"
url = "2.5"
chrono = "0.4"
config = "0.14"
toml = "0.8"
