[package]
name = "sol_beast"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40", features = ["full"] }
tokio-tungstenite = { version = "0.24", features = ["native-tls"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12" }
futures-util = "0.3"
log = "0.4"
env_logger = "0.11"
solana-program = "2.1.1"
solana-client = "2.1.1"
solana-sdk = "2.1.1"
base64 = "0.22"
url = "2.5.0"
borsh = "1.5"
lru = "0.12"
chrono = { version = "0.4", features = ["serde"] }
config = "0.14"
toml = "0.8"
mpl-token-metadata = "5.1.1"
rand = "0.8.5"

spl-token = { version = "4.0.1", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "3.0.2", features = ["no-entrypoint"] }
rust_decimal = { version = "1.39.0", features = ["serde"] }
rust_decimal_macros = "1.39.0"
